# Generated by Django 4.0.2 on 2022-05-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvonline',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cv',
        ),
        migrations.AddField(
            model_name='cvonline',
            name='cv',
            field=models.FileField(null=True, upload_to='CV Templates/%Y/%m'),
        ),
    ]
