# Generated by Django 4.0.2 on 2022-05-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_cvonline_job_id_remove_user_cv_cvonline_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvonline',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
