# Generated by Django 4.0.2 on 2022-05-04 07:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_lesson_comment_jobdetail_rating_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVOnline',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('intro', ckeditor.fields.RichTextField()),
                ('from_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('to_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserJobDetailView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('reading_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='pre_jobs',
            field=models.ManyToManyField(null=True, to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='viewers',
            field=models.ManyToManyField(through='jobs.UserJobDetailView', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'jobdetail')},
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.AddField(
            model_name='userjobdetailview',
            name='jobdetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobdetail'),
        ),
        migrations.AddField(
            model_name='userjobdetailview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='jobdetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobdetail'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userjobdetailview',
            unique_together={('user', 'jobdetail')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'jobdetail')},
        ),
    ]
