# Generated by Django 4.0.2 on 2022-05-09 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_cvonline_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvonline',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv', to=settings.AUTH_USER_MODEL),
        ),
    ]
