# Generated by Django 4.0.2 on 2022-05-06 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='pre_jobs',
        ),
    ]
