# Generated by Django 4.0.2 on 2022-05-06 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='jobs',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.company'),
        ),
    ]
